from GrafoDirigido import GrafoDirigido
from Nodo import Nodo

grafo = GrafoDirigido()

# Definición de nodos
nodo_a = Nodo('A')
nodo_b = Nodo('B')
nodo_c = Nodo('C')
nodo_d = Nodo('D')
nodo_e = Nodo('E')
nodo_f = Nodo('F')
nodo_g = Nodo('G')
nodo_h = Nodo('H')
nodo_i = Nodo('I')
nodo_j = Nodo('J')
nodo_k = Nodo('K')
nodo_l = Nodo('L')
nodo_m = Nodo('M')
nodo_n = Nodo('N')
nodo_o = Nodo('O')
nodo_p = Nodo('P')
nodo_q = Nodo('Q')
nodo_r = Nodo('R')
nodo_s = Nodo('S')
nodo_t = Nodo('T')
nodo_u = Nodo('U')
nodo_v = Nodo('V')
nodo_w = Nodo('W')
nodo_x = Nodo('X')
nodo_y = Nodo('Y')
nodo_z = Nodo('Z')
nodo_aa = Nodo('AA')
nodo_bb = Nodo('BB')
nodo_cc = Nodo('CC')
nodo_dd = Nodo('DD')
nodo_ee = Nodo('EE')
nodo_ff = Nodo('FF')
nodo_gg = Nodo('GG')
nodo_hh = Nodo('HH')
nodo_ii = Nodo('II')
nodo_jj = Nodo('JJ')
nodo_kk = Nodo('KK')
nodo_ll = Nodo('LL')
nodo_mm = Nodo('MM')
nodo_nn = Nodo('NN')
nodo_oo = Nodo('OO')
nodo_pp = Nodo('PP')
nodo_qq = Nodo('QQ')
nodo_rr = Nodo('RR')
nodo_ss = Nodo('SS')
nodo_tt = Nodo('TT')
nodo_uu = Nodo('UU')
nodo_vv = Nodo('VV')
nodo_ww = Nodo('WW')
nodo_xx = Nodo('XX')
nodo_yy = Nodo('YY')
nodo_zz = Nodo('ZZ')
nodo_ye = Nodo('YE')
nodo_pu = Nodo('PU')

# Agregar nodos al grafo
grafo.agregar_nodo(nodo_a)
grafo.agregar_nodo(nodo_b)
grafo.agregar_nodo(nodo_c)
grafo.agregar_nodo(nodo_d)
grafo.agregar_nodo(nodo_e)
grafo.agregar_nodo(nodo_f)
grafo.agregar_nodo(nodo_g)
grafo.agregar_nodo(nodo_h)
grafo.agregar_nodo(nodo_i)
grafo.agregar_nodo(nodo_j)
grafo.agregar_nodo(nodo_k)
grafo.agregar_nodo(nodo_l)
grafo.agregar_nodo(nodo_m)
grafo.agregar_nodo(nodo_n)
grafo.agregar_nodo(nodo_o)
grafo.agregar_nodo(nodo_p)
grafo.agregar_nodo(nodo_q)
grafo.agregar_nodo(nodo_r)
grafo.agregar_nodo(nodo_s)
grafo.agregar_nodo(nodo_t)
grafo.agregar_nodo(nodo_u)
grafo.agregar_nodo(nodo_v)
grafo.agregar_nodo(nodo_w)
grafo.agregar_nodo(nodo_x)
grafo.agregar_nodo(nodo_y)
grafo.agregar_nodo(nodo_z)
grafo.agregar_nodo(nodo_aa)
grafo.agregar_nodo(nodo_bb)
grafo.agregar_nodo(nodo_cc)
grafo.agregar_nodo(nodo_dd)
grafo.agregar_nodo(nodo_ee)
grafo.agregar_nodo(nodo_ff)
grafo.agregar_nodo(nodo_gg)
grafo.agregar_nodo(nodo_hh)
grafo.agregar_nodo(nodo_ii)
grafo.agregar_nodo(nodo_jj)
grafo.agregar_nodo(nodo_kk)
grafo.agregar_nodo(nodo_ll)
grafo.agregar_nodo(nodo_mm)
grafo.agregar_nodo(nodo_nn)
grafo.agregar_nodo(nodo_oo)
grafo.agregar_nodo(nodo_pp)
grafo.agregar_nodo(nodo_qq)
grafo.agregar_nodo(nodo_rr)
grafo.agregar_nodo(nodo_ss)
grafo.agregar_nodo(nodo_tt)
grafo.agregar_nodo(nodo_uu)
grafo.agregar_nodo(nodo_vv)
grafo.agregar_nodo(nodo_ww)
grafo.agregar_nodo(nodo_xx)
grafo.agregar_nodo(nodo_yy)
grafo.agregar_nodo(nodo_zz)
grafo.agregar_nodo(nodo_ye)
grafo.agregar_nodo(nodo_pu)



grafo.agregar_arista(nodo_a, nodo_b, 100, "Circular 74")
grafo.agregar_arista(nodo_a, nodo_c, 90, "Avenida Nutibara")
grafo.agregar_arista(nodo_a, nodo_d, 60, "Avenida Nutibara")
grafo.agregar_arista(nodo_b, nodo_a, 100, "Circular 74")
grafo.agregar_arista(nodo_b, nodo_e, 90, "Transversal 39")
grafo.agregar_arista(nodo_b, nodo_f, 60, "Transversal 39")
grafo.agregar_arista(nodo_b, nodo_j, 125, "Circular 74")
grafo.agregar_arista(nodo_c, nodo_a, 90, "Avenida Nutibara")
grafo.agregar_arista(nodo_c, nodo_g, 77, "Avenida Nutibara")
grafo.agregar_arista(nodo_d, nodo_a, 60, "Avenida Nutibara")
grafo.agregar_arista(nodo_d, nodo_f, 100, "Circular 74A")
grafo.agregar_arista(nodo_e, nodo_i, 77, "Transversal 39")
grafo.agregar_arista(nodo_e, nodo_c, 100, "Circular 73B")
grafo.agregar_arista(nodo_e, nodo_b, 90, "Transversal 39")
grafo.agregar_arista(nodo_f, nodo_b, 60, "Transversal 39")
grafo.agregar_arista(nodo_f, nodo_d, 100, "Circular 74A")
grafo.agregar_arista(nodo_f, nodo_h, 210, "Segundo Parque")
grafo.agregar_arista(nodo_g, nodo_c, 77, "Avenida Nutibara")
grafo.agregar_arista(nodo_g, nodo_k, 77, "Avenida Nutibara")
grafo.agregar_arista(nodo_g, nodo_i, 100, "Circular 73A")
grafo.agregar_arista(nodo_h, nodo_f, 40, "Segundo Parque")
grafo.agregar_arista(nodo_h, nodo_j, 90, "Carrera 76")
grafo.agregar_arista(nodo_i, nodo_e, 77, "Transversal 39")
grafo.agregar_arista(nodo_i, nodo_g, 100, "Circular 73A")
grafo.agregar_arista(nodo_i, nodo_l, 77, "Transversal 39")
grafo.agregar_arista(nodo_i, nodo_o, 105, "Circular 73A")
grafo.agregar_arista(nodo_j, nodo_h, 90, "Carrera 76")
grafo.agregar_arista(nodo_j, nodo_b, 125, "Circular 74")
grafo.agregar_arista(nodo_j, nodo_n, 70, "Carrera 76")
grafo.agregar_arista(nodo_k, nodo_g, 77, "Avenida Nutibara")
grafo.agregar_arista(nodo_k, nodo_ll, 180, "Avenida Nutibara")
grafo.agregar_arista(nodo_k, nodo_w, 50, "Circular 73")
grafo.agregar_arista(nodo_k, nodo_nn, 120, "Circular 4")
grafo.agregar_arista(nodo_l, nodo_i, 77, "Transversal 39")
grafo.agregar_arista(nodo_l, nodo_p, 70, "Circular 73")
grafo.agregar_arista(nodo_l, nodo_y, 180, "Transversal 39")
grafo.agregar_arista(nodo_m, nodo_e, 120, "Circular 73B")
grafo.agregar_arista(nodo_m, nodo_o, 95, "Transversal 38")
grafo.agregar_arista(nodo_n, nodo_j, 70, "Carrera 76")
grafo.agregar_arista(nodo_n, nodo_m, 60, "Circular 73B")
grafo.agregar_arista(nodo_n, nodo_q, 80, "Carrera 76")
grafo.agregar_arista(nodo_n, nodo_uu, 70, "Circular 73B")
grafo.agregar_arista(nodo_o, nodo_m, 95, "Transversal 38")
grafo.agregar_arista(nodo_o, nodo_i, 105, "Circular 73A")
grafo.agregar_arista(nodo_o, nodo_p, 90, "Transversal 38")
grafo.agregar_arista(nodo_o, nodo_q, 110, "Calle 35")
grafo.agregar_arista(nodo_o, nodo_t, 140, "Circular 73A")
grafo.agregar_arista(nodo_p, nodo_o, 90, "Transversal 38")
grafo.agregar_arista(nodo_p, nodo_r, 65, "Circular 73")
grafo.agregar_arista(nodo_p, nodo_z, 180, "Transversal 38")
grafo.agregar_arista(nodo_q, nodo_o, 110, "Calle 35")
grafo.agregar_arista(nodo_q, nodo_t, 90, "Carrera 76")
grafo.agregar_arista(nodo_q, nodo_vv, 70, "Calle 35")
grafo.agregar_arista(nodo_q, nodo_n, 80, "Carrera 76")
grafo.agregar_arista(nodo_r, nodo_s, 65, "Circular 73")
grafo.agregar_arista(nodo_r, nodo_aa, 180, "Transversal 37")
grafo.agregar_arista(nodo_s, nodo_v, 65, "Circular 73")
grafo.agregar_arista(nodo_s, nodo_bb, 180, "Transversal 36")
grafo.agregar_arista(nodo_t, nodo_q, 90, "Carrera 76")
grafo.agregar_arista(nodo_t, nodo_o, 140, "Circular 73A")
grafo.agregar_arista(nodo_t, nodo_u, 90, "Carrera 76")
grafo.agregar_arista(nodo_t, nodo_ww, 70, "Transversal 34A")
grafo.agregar_arista(nodo_u, nodo_t, 90, "Carrera 76")
grafo.agregar_arista(nodo_u, nodo_v, 50, "Circular 73")
grafo.agregar_arista(nodo_u, nodo_cc, 140, "Transversal 34")
grafo.agregar_arista(nodo_u, nodo_xx, 70, "Calle 34")
grafo.agregar_arista(nodo_v, nodo_u, 50, "Circular 73")
grafo.agregar_arista(nodo_v, nodo_ye, 180, "Transversal 35")
grafo.agregar_arista(nodo_w, nodo_l, 50, "Circular 73")
grafo.agregar_arista(nodo_w, nodo_x, 180, "Transversal 39A")
grafo.agregar_arista(nodo_x, nodo_w, 180, "Transversal 39A")
grafo.agregar_arista(nodo_x, nodo_ll, 50, "Circular 72")
grafo.agregar_arista(nodo_x, nodo_hh, 170, "Transversal 39A")
grafo.agregar_arista(nodo_y, nodo_x, 50, "Circular 72")
grafo.agregar_arista(nodo_y, nodo_z, 50, "Circular 72")
grafo.agregar_arista(nodo_y, nodo_gg, 170, "Transversal 39")
grafo.agregar_arista(nodo_z, nodo_p, 180, "Transversal 38")
grafo.agregar_arista(nodo_z, nodo_y, 50, "Circular 72")
grafo.agregar_arista(nodo_z, nodo_ff, 170, "Transversal 38")
grafo.agregar_arista(nodo_z, nodo_aa, 50, "Circular 72")
grafo.agregar_arista(nodo_aa, nodo_r, 180, "Transversal 37")
grafo.agregar_arista(nodo_aa, nodo_z, 50, "Circular 72")
grafo.agregar_arista(nodo_aa, nodo_ee, 125, "Transversal 37")
grafo.agregar_arista(nodo_aa, nodo_bb, 50, "Circular 72")
grafo.agregar_arista(nodo_bb, nodo_s, 180, "Transversal 36")
grafo.agregar_arista(nodo_bb, nodo_aa, 50, "Circular 72")
grafo.agregar_arista(nodo_bb, nodo_dd, 75, "Transversal 36")
grafo.agregar_arista(nodo_bb, nodo_ye, 50, "Circular 72")
grafo.agregar_arista(nodo_cc, nodo_u, 140, "Transversal 34")
grafo.agregar_arista(nodo_cc, nodo_zz, 70, "Calle 33A")
grafo.agregar_arista(nodo_cc, nodo_dd, 180, "Calle 33A")
grafo.agregar_arista(nodo_dd, nodo_bb, 75, "Transversal 36")
grafo.agregar_arista(nodo_dd, nodo_ee, 80, "Calle 33A")
grafo.agregar_arista(nodo_dd, nodo_cc, 180, "Calle 33A")
grafo.agregar_arista(nodo_ee, nodo_dd, 80, "Calle 33A")
grafo.agregar_arista(nodo_ee, nodo_aa, 125, "Transversal 37")
grafo.agregar_arista(nodo_ee, nodo_ff, 70, "Calle 33A")
grafo.agregar_arista(nodo_ff, nodo_ee, 70, "Calle 33A")
grafo.agregar_arista(nodo_ff, nodo_z, 170, "Transversal 38")
grafo.agregar_arista(nodo_ff, nodo_gg, 50, "Circular 71")
grafo.agregar_arista(nodo_ff, nodo_ii, 80, "Calle 33A")
grafo.agregar_arista(nodo_gg, nodo_ff, 50, "Circular 71")
grafo.agregar_arista(nodo_gg, nodo_y, 170, "Transversal 39")
grafo.agregar_arista(nodo_gg, nodo_hh, 50, "Circular 71")
grafo.agregar_arista(nodo_gg, nodo_ii, 67, "Transversal 39")
grafo.agregar_arista(nodo_hh, nodo_gg, 50, "Circular 71")
grafo.agregar_arista(nodo_hh, nodo_x, 170, "Transversal 39A")
grafo.agregar_arista(nodo_hh, nodo_kk, 50, "Circular 71")
grafo.agregar_arista(nodo_hh, nodo_jj, 110, "Transversal 39A")
grafo.agregar_arista(nodo_ii, nodo_ff, 80, "Calle 33A")
grafo.agregar_arista(nodo_ii, nodo_jj, 60, "Calle 33A")
grafo.agregar_arista(nodo_ii, nodo_gg, 67, "Transversal 39")
grafo.agregar_arista(nodo_jj, nodo_ii, 60, "Calle 33A")
grafo.agregar_arista(nodo_jj, nodo_hh, 110, "Transversal 39A")
grafo.agregar_arista(nodo_kk, nodo_hh, 50, "Circular 71")
grafo.agregar_arista(nodo_kk, nodo_ll, 175, "Avenida Nutibara")
grafo.agregar_arista(nodo_kk, nodo_qq, 235, "Circular 1")
grafo.agregar_arista(nodo_ll, nodo_kk, 175, "Avenida Nutibara")
grafo.agregar_arista(nodo_ll, nodo_k, 180, "Avenida Nutibara")
grafo.agregar_arista(nodo_ll, nodo_pp, 120, "Circular 2")
grafo.agregar_arista(nodo_mm, nodo_c, 115, "Circular 73B")
grafo.agregar_arista(nodo_mm, nodo_nn, 90, "Transversal 74")
grafo.agregar_arista(nodo_nn, nodo_mm, 90, "Transversal 74")
grafo.agregar_arista(nodo_nn, nodo_k, 120, "Circular 4")
grafo.agregar_arista(nodo_nn, nodo_oo, 70, "Transversal 74")
grafo.agregar_arista(nodo_oo, nodo_pp, 70, "Transversal 74")
grafo.agregar_arista(nodo_oo, nodo_pu, 120, "Circular 3")
grafo.agregar_arista(nodo_oo, nodo_nn, 70, "Transversal 74")
grafo.agregar_arista(nodo_oo, nodo_rr, 140, "Circular 3")
grafo.agregar_arista(nodo_pp, nodo_oo, 70, "Transversal 74")
grafo.agregar_arista(nodo_pp, nodo_ss, 140, "Circular 2")
grafo.agregar_arista(nodo_pp, nodo_qq, 70, "Transversal 74")
grafo.agregar_arista(nodo_pp, nodo_ll, 120, "Circular 2")
grafo.agregar_arista(nodo_qq, nodo_pp, 70, "Transversal 74")
grafo.agregar_arista(nodo_qq, nodo_kk, 235, "Circular 1")
grafo.agregar_arista(nodo_qq, nodo_tt, 140, "Circular 1")
grafo.agregar_arista(nodo_rr, nodo_ss, 75, "Carrera 73")
grafo.agregar_arista(nodo_rr, nodo_oo, 140, "Circular 3")
grafo.agregar_arista(nodo_ss, nodo_rr, 75, "Carrera 73")
grafo.agregar_arista(nodo_ss, nodo_tt, 60, "Carrera 73")
grafo.agregar_arista(nodo_ss, nodo_pp, 140, "Circular 2")
grafo.agregar_arista(nodo_tt, nodo_ss, 60, "Carrera 73")
grafo.agregar_arista(nodo_tt, nodo_qq, 140, "Circular 1")
grafo.agregar_arista(nodo_uu, nodo_n, 70, "Circular 73B")
grafo.agregar_arista(nodo_uu, nodo_vv, 80, "Carrera 77")
grafo.agregar_arista(nodo_vv, nodo_uu, 80, "Carrera 77")
grafo.agregar_arista(nodo_vv, nodo_q, 70, "Calle 35")
grafo.agregar_arista(nodo_vv, nodo_ww, 110, "Carrera 77")
grafo.agregar_arista(nodo_ww, nodo_vv, 110, "Carrera 77")
grafo.agregar_arista(nodo_ww, nodo_t, 70, "Transversal 34A")
grafo.agregar_arista(nodo_ww, nodo_xx, 100, "Carrera 77")
grafo.agregar_arista(nodo_xx, nodo_ww, 100, "Carrera 77")
grafo.agregar_arista(nodo_xx, nodo_u, 70, "Calle 34")
grafo.agregar_arista(nodo_xx, nodo_yy, 120, "Carrera 77")
grafo.agregar_arista(nodo_yy, nodo_xx, 120, "Carrera 77")
grafo.agregar_arista(nodo_yy, nodo_zz, 70, "Calle 33A")
grafo.agregar_arista(nodo_zz, nodo_yy, 70, "Calle 33A")
grafo.agregar_arista(nodo_zz, nodo_u, 90, "Carrera 76")
grafo.agregar_arista(nodo_zz, nodo_cc, 70, "Calle 33A")
grafo.agregar_arista(nodo_ye, nodo_v, 180, "Transversal 35")
grafo.agregar_arista(nodo_ye, nodo_bb, 50, "Circular 72")
grafo.agregar_arista(nodo_pu, nodo_k, 65, "Avenida Nutibara")
grafo.agregar_arista(nodo_pu, nodo_oo, 120, "Circular 3")
grafo.agregar_arista(nodo_pu, nodo_ll, 120, "Avenida Nutibara")

distancias = grafo.dijkstra('A')
print(f"La distancia más corta desde A a S es: {distancias['S']} metros")

#grafo.encontrar_camino("A", "S")